name: CI/CD - GHCR Build & Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd player-service-app
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd player-service-app
        pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ./player-service-app
        file: ./player-service-app/Dockerfile
        push: true
        tags: |
          ghcr.io/baoguixue/player-service:latest
          ghcr.io/baoguixue/player-service:${{ github.sha }}
          ${{ github.event.pull_request.number && format('ghcr.io/baoguixue/player-service:pr-{0}', github.event.pull_request.number) || '' }}
